export enum ProjectType {
  AGRO_TOURISM = 'AGRO_TOURISM',
  RESORT = 'RESORT',
  FARM_STAY = 'FARM_STAY',
  TOURISM_PLOTTING = 'TOURISM_PLOTTING',
  VILLA_RESORT = 'VILLA_RESORT',
  WELLNESS_RESORT = 'WELLNESS_RESORT',
  ECO_RESORT = 'ECO_RESORT',
  MIXED_TOURISM_DEVELOPMENT = 'MIXED_TOURISM_DEVELOPMENT',
}

export enum ProjectStatus {
  DRAFT = 'DRAFT',
  PLANNING = 'PLANNING',
  FEASIBILITY = 'FEASIBILITY',
  INVESTOR_REQUIRED = 'INVESTOR_REQUIRED',
  UNDER_DEVELOPMENT = 'UNDER_DEVELOPMENT',
  OPERATIONAL = 'OPERATIONAL',
  ON_HOLD = 'ON_HOLD',
  CLOSED = 'CLOSED',
}
