export enum LandStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  SITE_VISIT_REQUIRED = 'SITE_VISIT_REQUIRED',
  FEASIBLE = 'FEASIBLE',
  NOT_FEASIBLE = 'NOT_FEASIBLE',
  PROPOSAL_PREPARED = 'PROPOSAL_PREPARED',
  INVESTOR_REQUIRED = 'INVESTOR_REQUIRED',
  DEVELOPMENT_STARTED = 'DEVELOPMENT_STARTED',
  OPERATIONAL = 'OPERATIONAL',
}

export enum AreaUnit {
  ACRE = 'ACRE',
  GUNTHA = 'GUNTHA',
  HECTARE = 'HECTARE',
  SQFT = 'SQFT',
}

export enum DevelopmentInterest {
  AGRO_TOURISM = 'AGRO_TOURISM',
  RESORT = 'RESORT',
  FARM_STAY = 'FARM_STAY',
  TOURISM_PLOTTING = 'TOURISM_PLOTTING',
  VILLA_DEVELOPMENT = 'VILLA_DEVELOPMENT',
  WELLNESS_TOURISM = 'WELLNESS_TOURISM',
  ADVENTURE_TOURISM = 'ADVENTURE_TOURISM',
  NURSERY = 'NURSERY',
  ORGANIC_FARM = 'ORGANIC_FARM',
  MIXED_PROJECT = 'MIXED_PROJECT',
}
