import type { IKnowledgeChunk } from '../knowledge/knowledge.types';

export type PublicKnowledgeRecord = Pick<IKnowledgeChunk,
    'sourceType' | 'sourceName' | 'title' | 'category' | 'content' | 'metadata'> & { sourceId: string };

function service(id: string, title: string, content: string, sourcePath: string, sourceFile: string, section = title): PublicKnowledgeRecord {
    return {
        sourceType: 'SERVICE', sourceId: `service:${id}`, sourceName: 'Agrotourism Connect',
        category: 'SERVICES', title, content,
        metadata: { sourcePath, sourceFile: `frontend/src/pages/public/${sourceFile}.tsx`, section, managedBy: 'public-website-sync' },
    };
}

function publicRecord(sourceId: string, sourceType: PublicKnowledgeRecord['sourceType'], category: string,
    title: string, content: string, sourcePath: string, sourceFile: string): PublicKnowledgeRecord {
    return { sourceId, sourceType, category, title, content, sourceName: 'Agrotourism Connect',
        metadata: { sourcePath, sourceFile, section: title, managedBy: 'public-website-sync' } };
}

// Curated from the named public pages; these describe capabilities, not live listings.
export const PUBLIC_KNOWLEDGE: PublicKnowledgeRecord[] = [
    publicRecord('company:mission', 'COMPANY', 'ABOUT_SERVICES', 'Mission and Vision',
        'Agrotourism Connect aims to simplify sustainable agrotourism development and create lasting value for land, people and communities. Its vision is to guide projects from raw land to tourism destinations, bringing landowners, investors and developers together to collaborate.',
        '/about', 'frontend/src/pages/public/AboutPage.tsx'),
    publicRecord('company:development-process', 'COMPANY', 'ABOUT_SERVICES', 'Tourism Development Journey',
        'The website describes seven development stages: Land Submission, Project Feasibility, Plan & Design, Approvals & Legal, Development, Marketing & Sales, and Operations. They cover land details, site evaluation, concept development, documentation and statutory approvals, infrastructure and amenities, promotion and sales support, and resort operations and revenue sharing.',
        '/', 'frontend/src/pages/public/HomePage.tsx'),
    publicRecord('knowledge:center-overview', 'COMPANY', 'KNOWLEDGE_CENTER', 'Knowledge Center',
        'The Knowledge Center at /knowledge-center is the Agrotourism Connect resources section for guides and articles on agro tourism and land development. It currently displays topic cards under Guides & Articles and states: Detailed articles will be published here soon. Full articles and downloadable guides are not provided on this page yet.',
        '/knowledge-center', 'frontend/src/pages/public/KnowledgeCenterPage.tsx'),
    publicRecord('knowledge:center-topics', 'COMPANY', 'KNOWLEDGE_CENTER', 'Knowledge Center Topics and Contents',
        'The Knowledge Center contains six topic cards: Agro Tourism Basics; Land Development Process; Resort Planning Fundamentals; Understanding Investment Models; Tourism Activity Planning; and Working With Agrotourism Connect. These are displayed topics, not currently published full articles or courses.',
        '/knowledge-center', 'frontend/src/pages/public/KnowledgeCenterPage.tsx'),
    publicRecord('website:sections', 'COMPANY', 'PLATFORM_FEATURES', 'Website Sections and Navigation',
        'Public website sections include Home (/), About (/about), Agro Tourism (/agro-tourism), Land Development (/land-development), Resort Development (/resort-development), Investments (/investments), Projects (/projects), Services (/services), Gallery (/gallery), Knowledge Center (/knowledge-center), Contact (/contact), and Careers (/careers). Login and registration are available at /login and /register.',
        '/', 'frontend/src/App.tsx'),
    publicRecord('website:project-search', 'COMPANY', 'PLATFORM_FEATURES', 'Browsing Public Projects',
        'At /projects visitors can search published projects by name or location, filter by project type, and sort the displayed results by newest, oldest or name. Project cards show the published name, location, type, status, description and land area when available. Select View Project to open a project. This describes browsing functionality, not current project availability.',
        '/projects', 'frontend/src/pages/public/ProjectsPage.tsx'),
    publicRecord('website:project-types', 'COMPANY', 'PLATFORM_FEATURES', 'Project Type Filters',
        'The Projects page offers these project type filters: Agro Tourism, Resort, Farm Stay, Tourism Plotting, Villa Resort, Wellness Resort, Eco Resort and Mixed Tourism. A filter option does not establish that a project of that type is currently available.',
        '/projects', 'frontend/src/pages/public/ProjectsPage.tsx'),
    publicRecord('website:project-details', 'COMPANY', 'PLATFORM_FEATURES', 'Project Details and Enquiries',
        'Public project detail pages have Overview, Gallery, Details, Documents and Location tabs. Visitors can view published project information, use Share, or choose Enquire Now to visit the Contact page. The Documents tab currently displays a message that no public documents have been shared for the project.',
        '/projects', 'frontend/src/pages/public/ProjectDetailPage.tsx'),
    publicRecord('website:gallery', 'COMPANY', 'PLATFORM_FEATURES', 'Gallery',
        'The Gallery at /gallery displays images of projects, activities and landscapes. Visitors can select an image to enlarge it and close the enlarged view. Gallery imagery alone does not establish a named project or its availability.',
        '/gallery', 'frontend/src/pages/public/GalleryPage.tsx'),
    publicRecord('auth:registration', 'FAQ', 'LOGIN_AUTH', 'How to Register',
        'Open /register or choose a registration link such as List Your Land or Become an Investor. Provide full name, email, mobile and a password, and choose Landowner or Investor under I am a. City and state are optional. Public self-registration offers Landowner and Investor roles.',
        '/register', 'frontend/src/components/AuthModal.tsx'),
    publicRecord('website:landowner-account', 'FAQ', 'PLATFORM_FEATURES', 'Landowner Dashboard',
        'After signing in as a Landowner, the dashboard opens My Lands, where users can submit land and track their own submissions and review status. Submit Land opens a form for owner contact details, property title, location, survey or gat number, total area and area unit. Submit these details in the form, not the chatbot.',
        '/dashboard', 'frontend/src/pages/landowner/MyLandsPage.tsx'),
    publicRecord('investment:express-interest', 'FAQ', 'INVESTMENT', 'Expressing Investment Interest',
        'After signing in as an Investor, the dashboard shows Investment Opportunities with published projects and an action to express interest. My Interests lets investors track their submitted interests, including project, action, status and submission date. This describes account features, not a guarantee of available opportunities or returns.',
        '/dashboard', 'frontend/src/pages/investor/OpportunitiesPage.tsx'),
    publicRecord('website:investor-profile', 'FAQ', 'PLATFORM_FEATURES', 'Investor Profile',
        'Signed-in investors can maintain their Investor Profile, including investor name, company, contact details, city, state and preferred investment range. Use Save Profile to save changes. A preferred investment range is a user preference, not a published service price or investment offer.',
        '/dashboard/profile', 'frontend/src/pages/investor/InvestorProfilePage.tsx'),
    publicRecord('auth:login', 'FAQ', 'LOGIN_AUTH', 'Login and Account Access',
        'Open /login and enter your registered email and password to sign in. The login form includes Forgot password? and an option to switch to registration. Enter account credentials only in the website authentication form, not in the chatbot.',
        '/login', 'frontend/src/components/AuthModal.tsx'),
    publicRecord('auth:recovery', 'FAQ', 'LOGIN_AUTH', 'Forgot Password',
        'Choose Forgot password? on the login form or open /forgot-password and submit your email. The form says that if the email exists, a password reset link has been generated, and advises contacting support for help completing the reset. It does not promise email delivery.',
        '/forgot-password', 'frontend/src/components/AuthModal.tsx'),
    publicRecord('contact:email-location', 'CONTACT', 'CONTACT', 'Public Email and Location',
        'The Contact page lists info@agrotourismconnect.com as the public email address for Agrotourism Connect and gives its location as India. It also provides a contact form for enquiries.',
        '/contact', 'frontend/src/pages/public/ContactPage.tsx'),
    publicRecord('contact:enquiry-process', 'CONTACT', 'CONTACT', 'Sending an Enquiry',
        'At /contact, the Send Us a Message form asks for full name, mobile, email, city, requirement and message. Requirement examples include land acquisition, investment, partnership and resort development. Submit using Send Message; successful submission displays an acknowledgement that the enquiry was received.',
        '/contact', 'frontend/src/pages/public/ContactPage.tsx'),
    publicRecord('contact:instagram', 'CONTACT', 'CONTACT', 'Instagram',
        'The website links to Agrotourism Connect on Instagram at https://www.instagram.com/agrotourismconnect/.',
        '/', 'frontend/src/constants/social.ts'),
    publicRecord('careers:browsing', 'COMPANY', 'JOBS', 'Careers Page',
        'Visitors can browse public job listings at /careers and open View Details for a vacancy. Published vacancy pages can include department, location, employment type, openings, experience, salary and application deadline when supplied. This describes the careers feature and does not confirm any current vacancy.',
        '/careers', 'frontend/src/pages/public/CareersPage.tsx'),
    publicRecord('careers:application', 'FAQ', 'JOBS', 'Applying for a Published Vacancy',
        'Open a published vacancy from Careers and use its application form to submit your details and resume. The form includes name, email, phone, city, experience and additional professional information. A successful submission shows confirmation. This process description does not establish current job availability.',
        '/careers', 'frontend/src/pages/public/CareerDetailPage.tsx'),
    service('farm-stay', 'Farm Stay Development',
        'Farm stays are one of the resort development formats described by Agrotourism Connect, alongside eco resorts, villa resorts and wellness resorts. These developments are planned around the natural strengths, connectivity and tourism potential of the land.',
        '/resort-development', 'ResortDevelopmentPage'),
    service('project-development', 'Project Development Services',
        'The Services page describes end-to-end management of agro tourism and resort projects and structured land evaluation for tourism potential.',
        '/services', 'ServicesPage'),
    service('investor-facilitation', 'Investor Facilitation',
        'The Services page describes investor facilitation as connecting vetted investors with planned projects. This is a service description, not confirmation of a particular opportunity or financial terms.',
        '/services', 'ServicesPage'),
    service('relationship-management', 'CRM and Relationship Management',
        'The public Services page describes CRM & Relationship Management as structured lead management and follow-ups for every stakeholder.',
        '/services', 'ServicesPage'),
    service('farm-activities', 'Farm Activities',
        'The Agro Tourism page lists Farm Tour, Fruit Picking, Plantation and Organic Farming Demo under Farm Activities. These are activity concepts presented by the website, not a dated or bookable event schedule.',
        '/agro-tourism', 'AgroTourismPage'),
    service('nature-activities', 'Nature Activities',
        'The Agro Tourism page lists Nature Trail, Bird Watching, Photography and Trekking under Nature.',
        '/agro-tourism', 'AgroTourismPage'),
    service('wellness-activities', 'Wellness Activities',
        'The Agro Tourism page lists Yoga, Meditation, Herbal Garden and Healthy Food under Wellness.',
        '/agro-tourism', 'AgroTourismPage'),
    service('food-experiences', 'Food Experiences',
        'The Agro Tourism page lists Farm-to-Table, Local Cuisine, Fresh Juice and Bonfire Dinner under Food.',
        '/agro-tourism', 'AgroTourismPage'),
    {
        sourceType: 'COMPANY',
        sourceId: 'company:overview',
        sourceName: 'Agrotourism Connect',
        category: 'ABOUT_SERVICES',
        title: 'About Agrotourism Connect',
        content:
            'Agrotourism Connect is a platform for the complete journey of turning land into a tourism asset, from land submission through feasibility, planning, investment, development and tourism operations. It brings together landowners, investors, agro tourism developers, resort operators, tourism consultants, farmers and service providers to track progress and collaborate.',
        metadata: {
            sourcePath: '/about',
            sourceFile: 'frontend/src/pages/public/AboutPage.tsx',
            section: 'Our Story',
            managedBy: 'public-website-sync',
        },
    },

    {
        sourceType: 'SERVICE',
        sourceId: 'service:land-evaluation',
        sourceName: 'Agrotourism Connect',
        category: 'SERVICES',
        title: 'Land Advisory and Land Evaluation',
        content:
            'Agrotourism Connect provides land advisory to identify, evaluate and acquire suitable land for agro tourism projects. Its project feasibility process includes site evaluation and feasibility analysis.',
        metadata: {
            sourcePath: '/',
            sourceFile: 'frontend/src/pages/public/HomePage.tsx',
            section: 'Core Services / Project Feasibility',
            managedBy: 'public-website-sync',
        },
    },

    service('core-services', 'Agrotourism Connect — Core Services',
        'Agrotourism Connect focuses on tourism development through Land Development, Resort Development and Agro Tourism. Its core services include Land Advisory, Project Planning, Approvals & Legal, Development Support, Marketing & Sales, and Operations Support. Project planning includes feasibility studies, DPR, concept planning and designing.',
        '/', 'HomePage', 'Core Services / heroServiceCards'),
    service('land-development', 'Land Development',
        'Agrotourism Connect helps owners of agricultural or open land with tourism potential submit land details, location and infrastructure information, upload photos, videos and land documents, and track review status through development. Landowners can connect with investors and developers once their project is ready.',
        '/land-development', 'LandDevelopmentPage'),
    service('resort-development', 'Resort Development',
        'Resort development on Agrotourism Connect covers farm stays, eco resorts, villa resorts and wellness resorts, planned around the land\'s natural strengths, connectivity and tourism potential. The public page showcases premium cottages, A-frame cottages, POD/prefab cottages, pools, landscaping and landscaped gazebos.',
        '/resort-development', 'ResortDevelopmentPage'),
    service('agro-tourism', 'Agro Tourism',
        'Agrotourism Connect describes agro tourism as combining agriculture, tourism, hospitality, nature, activities, food, culture and wellness. Its concept is Grow + Stay + Experience + Earn: farming and plantation, stays in cottages, villas or farm stays, and visitor experiences. Examples on the public page include farm tours, fruit picking, nature trails, bird watching, yoga and farm-to-table food.',
        '/agro-tourism', 'AgroTourismPage'),
    service('feasibility-planning', 'Tourism Feasibility and Project Planning',
        'Agrotourism Connect provides project planning including feasibility studies, DPR, concept planning and designing. Project feasibility involves site evaluation and feasibility analysis, followed by planning and concept development for tourism projects.',
        '/', 'HomePage', 'Project Planning / Project Feasibility / Plan & Design'),
    service('approvals-legal', 'Approvals & Legal',
        'Agrotourism Connect offers documentation, legal compliance and regulatory approvals support as part of its tourism development services.',
        '/', 'HomePage', 'Core Services'),
    service('development-support', 'Development Support',
        'Agrotourism Connect offers infrastructure, amenities and landscaping development assistance for tourism projects.',
        '/', 'HomePage', 'Core Services'),
    service('marketing-sales', 'Marketing & Sales',
        'Agrotourism Connect offers project branding, digital marketing and sales support.',
        '/', 'HomePage', 'Core Services'),
    service('operations-support', 'Operations Support',
        'Agrotourism Connect offers operational guidance, revenue optimization and ongoing support.',
        '/', 'HomePage', 'Core Services'),
    service('investment-platform', 'Investment Platform Services',
        'The Agrotourism Connect investment page displays published agro tourism and resort projects for investment discussions and provides registration to express interest. Financial details are shared with registered, authorized investors. Investment structures and returns are not guaranteed and require independent legal and financial due diligence. This describes the platform service; it does not establish that any specific investment opportunity is currently available.',
        '/investments', 'InvestmentsPage'),
    {
        sourceType: 'CONTACT',
        sourceId: 'contact:website-form',
        sourceName: 'Agrotourism Connect',
        category: 'CONTACT',
        title: 'Contact Agrotourism Connect',
        content:
            'For land, investment, partnership or tourism development enquiries, users can contact Agrotourism Connect through the contact form on the website.',
        metadata: {
            sourcePath: '/contact',
            sourceFile: 'frontend/src/pages/public/ContactPage.tsx',
            section: 'Contact Form',
            managedBy: 'public-website-sync',
        },
    },
];
