export enum ApprovalType {
  LAND_CONVERSION = 'LAND_CONVERSION',
  ENVIRONMENTAL_CLEARANCE = 'ENVIRONMENTAL_CLEARANCE',
  BUILDING_PLAN = 'BUILDING_PLAN',
  FIRE_NOC = 'FIRE_NOC',
  TOURISM_LICENSE = 'TOURISM_LICENSE',
  WATER_NOC = 'WATER_NOC',
  ELECTRICITY_CONNECTION = 'ELECTRICITY_CONNECTION',
  POLLUTION_CONTROL = 'POLLUTION_CONTROL',
  FOOD_LICENSE = 'FOOD_LICENSE',
  LIQUOR_LICENSE = 'LIQUOR_LICENSE',
  LABOUR_LICENSE = 'LABOUR_LICENSE',
  OTHER = 'OTHER',
}

export enum ApprovalStatus {
  NOT_STARTED = 'NOT_STARTED',
  APPLIED = 'APPLIED',
  UNDER_PROCESS = 'UNDER_PROCESS',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}
