export enum LeadSource {
  WEBSITE = 'WEBSITE',
  WHATSAPP = 'WHATSAPP',
  FACEBOOK = 'FACEBOOK',
  INSTAGRAM = 'INSTAGRAM',
  GOOGLE_ADS = 'GOOGLE_ADS',
  REFERRAL = 'REFERRAL',
  EXISTING_CUSTOMER = 'EXISTING_CUSTOMER',
  EVENT = 'EVENT',
  BROKER = 'BROKER',
  OTHER = 'OTHER',
}

export enum LeadType {
  LANDOWNER = 'LANDOWNER',
  INVESTOR = 'INVESTOR',
  CUSTOMER = 'CUSTOMER',
  RESORT_OPERATOR = 'RESORT_OPERATOR',
  DEVELOPER = 'DEVELOPER',
  SERVICE_PROVIDER = 'SERVICE_PROVIDER',
}

export enum LeadStatus {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  INTERESTED = 'INTERESTED',
  FOLLOW_UP = 'FOLLOW_UP',
  MEETING_SCHEDULED = 'MEETING_SCHEDULED',
  SITE_VISIT_SCHEDULED = 'SITE_VISIT_SCHEDULED',
  PROPOSAL_SENT = 'PROPOSAL_SENT',
  NEGOTIATION = 'NEGOTIATION',
  CONVERTED = 'CONVERTED',
  LOST = 'LOST',
  NOT_INTERESTED = 'NOT_INTERESTED',
}
