export enum WorkItemCategory {
  ROAD = 'ROAD',
  WATER = 'WATER',
  ELECTRICITY = 'ELECTRICITY',
  DRAINAGE = 'DRAINAGE',
  LANDSCAPING = 'LANDSCAPING',
  PLANTATION = 'PLANTATION',
  COTTAGE_VILLA = 'COTTAGE_VILLA',
  POOL = 'POOL',
  RESTAURANT = 'RESTAURANT',
  GAZEBO = 'GAZEBO',
  AMENITIES = 'AMENITIES',
  OTHER = 'OTHER',
}

export enum WorkItemStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  ON_HOLD = 'ON_HOLD',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
