export enum InvestmentType {
  EQUITY = 'EQUITY',
  PROFIT_PARTICIPATION = 'PROFIT_PARTICIPATION',
  PROJECT_INVESTMENT = 'PROJECT_INVESTMENT',
  DEBT = 'DEBT',
  STRATEGIC = 'STRATEGIC',
  OTHER = 'OTHER',
}

export enum InvestmentStatus {
  INTERESTED = 'INTERESTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  DUE_DILIGENCE = 'DUE_DILIGENCE',
  COMMITTED = 'COMMITTED',
  PARTIALLY_FUNDED = 'PARTIALLY_FUNDED',
  FUNDED = 'FUNDED',
  WITHDRAWN = 'WITHDRAWN',
  REJECTED = 'REJECTED',
  CLOSED = 'CLOSED',
}

export enum DueDiligenceStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum PaymentMode {
  BANK_TRANSFER = 'BANK_TRANSFER',
  CHEQUE = 'CHEQUE',
  UPI = 'UPI',
  CASH = 'CASH',
  OTHER = 'OTHER',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}
