export enum MilestoneCategory {
  PLANNING = 'PLANNING',
  APPROVAL = 'APPROVAL',
  INFRASTRUCTURE = 'INFRASTRUCTURE',
  CONSTRUCTION = 'CONSTRUCTION',
  LANDSCAPING = 'LANDSCAPING',
  PLANTATION = 'PLANTATION',
  AMENITIES = 'AMENITIES',
  OPERATIONS_READINESS = 'OPERATIONS_READINESS',
  OTHER = 'OTHER',
}

export enum MilestoneStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  DELAYED = 'DELAYED',
  COMPLETED = 'COMPLETED',
  ON_HOLD = 'ON_HOLD',
  CANCELLED = 'CANCELLED',
}
